[polkit]
background       = "#c4c6d1"
background-alpha = 1.0
text             = "#101010"
text-error       = "#aa0000"
border           = "hyprland.active-border"
border-error     = "#aa0000"
border-alpha     = 1.0
scrim            = "#010378"
scrim-alpha      = 0.5
accent           = "#010378"
